### ISSUE TITLE
Setup rest-assured in this repo

### ISSUE THREAD

**Issue by vydra** [qe-study-group/MealieLab#3]
What build tool?
Gradle !!!!

JDK?

**Comment by jmeowmeow** [comment]
This is an issue with the GitHub Codespace image that strips down the jsoup jar because of a vulnerability. This is done by GitHub and cannot be addressed in the Gradle Build Tool project.

More recent versions of Gradle ship an updated jsoup jar that should not cause this problem.

from https://github.com/gradle/gradle/issues/23730

**Comment by vydra** [comment]
This was a fun exercise in installing retro-dependencies to overcome security and bytecode incompatibilities.
